"""Generate sp_hex_w_matrix_hd<head_dim>.h — compile-time W-matrix for the
Hierarchical Spinor predictor (Strike 11).

The Hierarchical path replaces the Strike-9 pipeline
    VHT2 -> Mobius scatter -> band_quantize (5/5/4/3)
with
    VHT2(mixed-radix 154) -> skeleton extract -> W * skeleton -> residual quant

The W matrix is shape (predicted_size, skeleton_size) = (140, 14) for the
default 154 = 2*7*11 mixed-radix layout (14 Knight skeleton coords + 140
residual coords).

LAYOUT — COLUMN-MAJOR. The access pattern in the DSP kernel is:

    for j in 0..skeleton_size:          # outer over skeleton elements
        s_j = skeleton[j]               # broadcast across HVX lanes
        for chunk in 0..predicted_size, step 64:
            v_w = vmem load 64 int16   # one column slice from rodata
            v_acc[chunk] += s_j * v_w   # vmpyiwh_acc / vmpyieacc

Column-major means W[i,j] for fixed j is contiguous in memory, so each
inner-vector load pulls 64 W values from one skeleton column with no
strided gather. Cross-lane permutations: zero.

QUANTIZATION — Q15 fixed-point (int16). The V69 lacks native fp16 vector
MAC instructions, but executes 64 int16*int16 -> int32 MACs per cycle.
We scale calibrated fp32 weights by 32767 and round to int16. The kernel
restores fp32 by dividing the int32 accumulator by 32767 (single vasr
+ vasl recombine).

CALIBRATION — for now this generator emits a deterministic pseudo-random
distribution scaled to 0.05 * N(0,1) so the parity test has stable
weights across Linux/Windows runs. The real generator drops the SVD-
calibrated weights into the same slot when calibration lands.
"""

import os
import struct

import numpy as np


# ----------------------------------------------------------------------------
# Output paths — match the gen_mobius_tables.py convention.
# ----------------------------------------------------------------------------
def repo_hexagon_dir():
    """Resolve <repo>/lib/shannon-prime/backends/hexagon regardless of cwd."""
    this = os.path.abspath(__file__)
    scripts_dir = os.path.dirname(this)
    repo = os.path.dirname(scripts_dir)
    return os.path.join(repo, "lib", "shannon-prime", "backends", "hexagon")


# ----------------------------------------------------------------------------
# Calibration source — placeholder until SVD pipeline lands.
# ----------------------------------------------------------------------------
def calibrated_w_matrix(predicted_size, skeleton_size, seed_offset):
    """Return a fp32 W matrix of shape (predicted_size, skeleton_size).

    For Strike 11 scaffold this is deterministic pseudo-random; the seed
    is keyed off head_dim so each supported config has stable weights.
    Replace this function body with the SVD-calibrated load when the
    calibration pipeline ships.
    """
    rng = np.random.default_rng(seed=42 + seed_offset)
    W = rng.standard_normal((predicted_size, skeleton_size)) * 0.05
    return W.astype(np.float32)


# ----------------------------------------------------------------------------
# Q15 quantize + max-abs reporting for the parity test budget.
# ----------------------------------------------------------------------------
def quantize_q15(W_float):
    """fp32 (predicted, skeleton) -> int16 (predicted, skeleton) in Q15."""
    Q_SCALE = 32767.0
    W_scaled = np.round(W_float * Q_SCALE)
    W_q15 = np.clip(W_scaled, -32768, 32767).astype(np.int16)
    abs_err = np.max(np.abs(W_float - W_q15.astype(np.float32) / Q_SCALE))
    return W_q15, abs_err


# ----------------------------------------------------------------------------
# Header emitter.
# ----------------------------------------------------------------------------
def emit_header(head_dim, skeleton_size, predicted_size, W_q15, abs_err,
                out_dir):
    """Write sp_hex_w_matrix_hd<head_dim>.h with the column-major Q15 W."""
    assert W_q15.shape == (predicted_size, skeleton_size)
    assert W_q15.dtype == np.int16

    fname = os.path.join(out_dir, f"sp_hex_w_matrix_hd{head_dim}.h")
    total_elems = predicted_size * skeleton_size
    total_bytes = total_elems * 2  # int16

    lines = []
    lines.append(
        f"// Auto-generated by scripts/gen_w_matrix.py — do not hand-edit.")
    lines.append(
        f"// W-matrix for Hierarchical Spinor predictor, head_dim={head_dim}.")
    lines.append(
        f"//   shape  : ({predicted_size}, {skeleton_size})  "
        f"= (predicted, skeleton)")
    lines.append(
        f"//   layout : COLUMN-MAJOR, int16 Q15 fixed-point")
    lines.append(
        f"//   bytes  : {total_bytes} ({predicted_size}*{skeleton_size}*2)")
    lines.append(
        f"//   max abs quant error (fp32 vs Q15): {abs_err:.3e}")
    lines.append("//")
    lines.append("// Access pattern: skeleton element j is one contiguous run")
    lines.append("// of `predicted_size` int16 starting at offset")
    lines.append("//   j * predicted_size * sizeof(int16).")
    lines.append("//")
    lines.append("// To restore fp32: out_f32 = acc_i32 / 32767.0f.  This is a")
    lines.append("// single vasr by 15 + correction term on the DSP side (the")
    lines.append("// kernel handles it inline; callers see fp32).")
    lines.append("")
    lines.append("#ifndef SP_HEX_W_MATRIX_HD" + str(head_dim) + "_H")
    lines.append("#define SP_HEX_W_MATRIX_HD" + str(head_dim) + "_H")
    lines.append("")
    lines.append("#include <stdint.h>")
    lines.append("")
    lines.append(f"#define SP_HEX_W_MATRIX_HD{head_dim}_SKELETON {skeleton_size}")
    lines.append(f"#define SP_HEX_W_MATRIX_HD{head_dim}_PREDICTED {predicted_size}")
    lines.append("")
    lines.append(
        f"static const int16_t sp_hex_w_matrix_hd{head_dim}[{total_elems}]")
    lines.append("    __attribute__((aligned(128))) = {")

    # Column-major dump: for each skeleton column j, walk predicted rows i.
    for j in range(skeleton_size):
        lines.append(f"    /* skeleton element {j} */")
        col_vals = W_q15[:, j]
        # 16 values per source line for readability.
        for chunk_start in range(0, predicted_size, 16):
            chunk = col_vals[chunk_start:chunk_start + 16]
            lines.append("    " + ", ".join(f"{int(v):6d}" for v in chunk) + ",")
        lines.append("")

    # Drop the trailing blank line before the closing brace.
    while lines and lines[-1] == "":
        lines.pop()
    lines.append("};")
    lines.append("")
    lines.append("#endif  // SP_HEX_W_MATRIX_HD" + str(head_dim) + "_H")
    lines.append("")

    os.makedirs(out_dir, exist_ok=True)
    with open(fname, "w", newline="\n") as f:
        f.write("\n".join(lines))
    print(f"[gen_w_matrix] wrote {fname} ({total_bytes} bytes, "
          f"max quant err {abs_err:.3e})")
    return fname


# ----------------------------------------------------------------------------
# Public entry — sweep all supported (head_dim, skeleton, predicted) configs.
# ----------------------------------------------------------------------------
CONFIGS = [
    # head_dim must factor as 2 * <other primes>; the skeleton size is the
    # product of the smaller radices and the predicted count is the rest.
    # 154 = 2 * 7 * 11.  Skeleton picks the 14 Knight coords (2 * 7), so the
    # remaining 140 = 154 - 14 are residual.
    {"head_dim": 154, "skeleton_size": 14, "predicted_size": 140},
]


def main():
    out_dir = repo_hexagon_dir()
    print(f"[gen_w_matrix] target dir: {out_dir}")
    for cfg in CONFIGS:
        hd  = cfg["head_dim"]
        sk  = cfg["skeleton_size"]
        pr  = cfg["predicted_size"]
        assert sk + pr == hd, (
            f"skeleton+predicted ({sk}+{pr}) must equal head_dim ({hd})")
        W = calibrated_w_matrix(pr, sk, seed_offset=hd)
        W_q15, err = quantize_q15(W)
        emit_header(hd, sk, pr, W_q15, err, out_dir)


if __name__ == "__main__":
    main()
