"""Generate sp_hex_mobius_tables.c — compile-time Möbius scatter offsets.

For each supported head_dim, emits the inverse-permutation byte offset table
that the HVX scatter kernel loads. Semantics:

    scalar reorder:  out[i] = in[order[i]]               (gather)
    scatter form:    out[inv_order[j]] = in[j]           (write per j)

The HVX vscatter instruction writes src[j] to address (Rt + offsets[j]) for
each lane j. So we bake offsets[j] = inv_order[j] * sizeof(element).

Möbius mask μ(n):
  μ(1) = 1
  μ(n) = 0  if n has a squared prime factor
  μ(n) = (-1)^k  if n is a product of k distinct primes

The squarefree-first reorder pushes indices with μ(i) != 0 to the front,
non-squarefree (μ(i) == 0) to the back. Deterministic from head_dim alone.

Output: lib/shannon-prime/backends/hexagon/sp_hex_mobius_tables.c
        with one static const uint32_t[head_dim] per supported head_dim,
        a dispatcher sp_hex_mobius_offsets_f32(head_dim), and an
        sp_hex_mobius_supported_head_dim(head_dim) predicate.
"""

import os


def compute_mobius(n):
    """μ-sieve for indices [0, n)."""
    mu = [0] * n
    if n > 1:
        mu[1] = 1
    prime_count = [0] * n
    has_square = [False] * n
    for p in range(2, n):
        if prime_count[p] != 0:
            continue
        for m in range(p, n, p):
            prime_count[m] += 1
        p2 = p * p
        if p2 < n:
            for m in range(p2, n, p2):
                has_square[m] = True
    for i in range(2, n):
        if has_square[i]:
            mu[i] = 0
        else:
            mu[i] = 1 if prime_count[i] % 2 == 0 else -1
    return mu


def compute_inv_order(n):
    """Return inv_order[j] = output position of source index j."""
    mu = compute_mobius(n)
    sf  = [i for i in range(n) if mu[i] != 0]
    nsf = [i for i in range(n) if mu[i] == 0]
    order = sf + nsf        # order[i] = source index for output position i
    inv = [0] * n
    for i, j in enumerate(order):
        inv[j] = i
    return inv, len(sf)


def emit_table(head_dim, element_size):
    """Return C source for the scatter offset table at this head_dim.
    Byte offsets pre-multiplied by element size so vscatter can read directly."""
    inv, n_sf = compute_inv_order(head_dim)
    offsets = [pos * element_size for pos in inv]
    # Sanity: offsets must be in [0, head_dim * element_size), each value unique
    assert len(set(offsets)) == head_dim
    assert all(0 <= b < head_dim * element_size for b in offsets)

    name = f"sp_hex_mobius_offsets_hd{head_dim}_f32"
    lines = [
        f"/* head_dim={head_dim}, n_squarefree={n_sf}, "
        f"element_size={element_size}.  Byte offsets for vscatter into a "
        f"{head_dim * element_size}-byte VTCM region. */",
        f"static const uint32_t {name}[{head_dim}] __attribute__((aligned(128))) = {{",
    ]
    for i in range(0, head_dim, 8):
        chunk = ", ".join(f"{v:5d}u" for v in offsets[i:i + 8])
        lines.append(f"    {chunk},")
    lines.append("};")
    lines.append("")
    return "\n".join(lines), n_sf


def main():
    HEAD_DIMS = [64, 128, 256, 512]
    ELEMENT_SIZE = 4  # fp32

    here = os.path.dirname(os.path.abspath(__file__))
    out_path = os.path.normpath(os.path.join(
        here, "..", "lib", "shannon-prime", "backends", "hexagon",
        "sp_hex_mobius_tables.c"))

    body = []
    body.append("/* sp_hex_mobius_tables.c — auto-generated by")
    body.append(" * scripts/gen_mobius_tables.py.  Compile-time byte-offset tables")
    body.append(" * for HVX vscatter-based Möbius reorder, one per supported")
    body.append(" * head_dim.  See the script docstring for the math derivation.")
    body.append(" *")
    body.append(" * DO NOT EDIT BY HAND — regenerate via:")
    body.append(" *   python scripts/gen_mobius_tables.py")
    body.append(" */")
    body.append("")
    body.append('#include "sp_hex_mobius_tables.h"')
    body.append("")

    n_sf_by_dim = {}
    for hd in HEAD_DIMS:
        block, n_sf = emit_table(hd, ELEMENT_SIZE)
        body.append(block)
        n_sf_by_dim[hd] = n_sf

    body.append("/* Dispatcher: return the byte-offset table for the requested")
    body.append(" * head_dim, or NULL if unsupported (caller falls back to scalar). */")
    body.append("const uint32_t* sp_hex_mobius_offsets_f32(int head_dim) {")
    body.append("    switch (head_dim) {")
    for hd in HEAD_DIMS:
        body.append(f"    case {hd:4d}: return sp_hex_mobius_offsets_hd{hd}_f32;")
    body.append("    default: return (const uint32_t*)0;")
    body.append("    }")
    body.append("}")
    body.append("")
    body.append("int sp_hex_mobius_supported_head_dim(int head_dim) {")
    body.append("    return sp_hex_mobius_offsets_f32(head_dim) ? 1 : 0;")
    body.append("}")
    body.append("")
    body.append("int sp_hex_mobius_n_squarefree(int head_dim) {")
    body.append("    switch (head_dim) {")
    for hd, n in n_sf_by_dim.items():
        body.append(f"    case {hd:4d}: return {n};")
    body.append("    default: return -1;")
    body.append("    }")
    body.append("}")
    body.append("")

    text = "\n".join(body)
    with open(out_path, "w", encoding="utf-8") as f:
        f.write(text)

    print(f"Wrote {out_path} ({len(text)} bytes)")
    print("Möbius reorder n_squarefree per head_dim:")
    for hd, n in n_sf_by_dim.items():
        print(f"  hd={hd:4d}  n_squarefree={n:4d}  ({100.0*n/hd:.1f}% of vector)")


if __name__ == "__main__":
    main()
